import { describe, it, expect } from 'vitest';
import { normalizeType, importDDL } from './ddl-import';
import { parseRefAction } from './ddl-import-types';

// ═════════════════════════════════════════════
// Oracle
// ═════════════════════════════════════════════
describe('importDDL — Oracle', () => {
  // --- Basic parsing ---
  it('parses basic CREATE TABLE', async () => {
    const sql = `
      CREATE TABLE employees (
        id DECIMAL(10) NOT NULL,
        name VARCHAR(100) NOT NULL,
        bio TEXT,
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.errors).toHaveLength(0);
    expect(result.tables).toHaveLength(1);
    expect(result.tables[0].columns).toHaveLength(3);
  });

  // --- Type mapping ---
  it('maps Oracle types: VARCHAR2→VARCHAR, CLOB→TEXT, NUMBER→DECIMAL', async () => {
    const sql = `
      CREATE TABLE test (
        a VARCHAR2(100),
        b CLOB,
        c NUMBER(10),
        d NCLOB
      );
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.errors).toHaveLength(0);
    const cols = result.tables[0].columns;
    expect(cols.find(c => c.name === 'a')!.type).toBe('VARCHAR');
    expect(cols.find(c => c.name === 'b')!.type).toBe('TEXT');
    expect(cols.find(c => c.name === 'c')!.type).toBe('DECIMAL');
    expect(cols.find(c => c.name === 'd')!.type).toBe('TEXT');
  });

  it('maps DOUBLE PRECISION→DOUBLE, FLOAT→FLOAT', async () => {
    const sql = `
      CREATE TABLE test (
        a DOUBLE PRECISION,
        b FLOAT
      );
    `;
    const result = await importDDL(sql, 'oracle');
    const cols = result.tables[0].columns;
    expect(cols.find(c => c.name === 'a')!.type).toBe('DOUBLE');
    expect(cols.find(c => c.name === 'b')!.type).toBe('FLOAT');
  });

  it('maps VARCHAR2 → VARCHAR', async () => {
    const sql = `
      CREATE TABLE test (
        code VARCHAR(10) NOT NULL
      );
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].columns[0].type).toBe('VARCHAR');
  });

  // --- IDENTITY ---
  it('detects GENERATED ALWAYS AS IDENTITY', async () => {
    const sql = `
      CREATE TABLE test (
        id NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
        name VARCHAR2(100),
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    const idCol = result.tables[0].columns.find(c => c.name === 'id')!;
    expect(idCol.autoIncrement).toBe(true);
  });

  it('detects GENERATED BY DEFAULT AS IDENTITY', async () => {
    const sql = `
      CREATE TABLE test (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR2(100),
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    const idCol = result.tables[0].columns.find(c => c.name === 'id')!;
    expect(idCol.autoIncrement).toBe(true);
  });

  it('detects IDENTITY with START WITH/INCREMENT BY options', async () => {
    const sql = `
      CREATE TABLE test (
        id NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
        name VARCHAR2(100),
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    const idCol = result.tables[0].columns.find(c => c.name === 'id')!;
    expect(idCol.autoIncrement).toBe(true);
  });

  // --- COMMENT ON ---
  it('applies COMMENT ON TABLE and COLUMN', async () => {
    const sql = `
      CREATE TABLE items (
        id DECIMAL(10) NOT NULL,
        name VARCHAR(100)
      );
      COMMENT ON TABLE items IS 'Item master table';
      COMMENT ON COLUMN items.name IS 'Item name';
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].comment).toBe('Item master table');
    expect(result.tables[0].columns.find(c => c.name === 'name')!.comment).toBe('Item name');
  });

  it('handles multiple COMMENT ON for different columns', async () => {
    const sql = `
      CREATE TABLE test (
        a INT NOT NULL,
        b VARCHAR(100),
        c VARCHAR(100)
      );
      COMMENT ON TABLE test IS 'Test table';
      COMMENT ON COLUMN test.a IS 'Column A';
      COMMENT ON COLUMN test.b IS 'Column B';
      COMMENT ON COLUMN test.c IS 'Column C';
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].comment).toBe('Test table');
    const cols = result.tables[0].columns;
    expect(cols.find(c => c.name === 'a')!.comment).toBe('Column A');
    expect(cols.find(c => c.name === 'b')!.comment).toBe('Column B');
    expect(cols.find(c => c.name === 'c')!.comment).toBe('Column C');
  });

  // --- Oracle keyword stripping ---
  it('strips Oracle keywords: ENABLE, TABLESPACE, STORAGE, etc.', async () => {
    const sql = `
      CREATE TABLE test (
        id DECIMAL(10) NOT NULL,
        name VARCHAR(100),
        CONSTRAINT pk_test PRIMARY KEY (id) ENABLE
      ) TABLESPACE users PCTFREE 10 INITRANS 2 STORAGE (INITIAL 65536) LOGGING;
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.errors).toHaveLength(0);
    expect(result.tables).toHaveLength(1);
  });

  // --- / batch separator ---
  it('handles / batch separator', async () => {
    const sql = `
      CREATE TABLE test1 (
        id DECIMAL(10) NOT NULL,
        PRIMARY KEY (id)
      );
      /
      CREATE TABLE test2 (
        id DECIMAL(10) NOT NULL,
        PRIMARY KEY (id)
      );
      /
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables).toHaveLength(2);
  });

  // --- PK ---
  it('handles composite primary key', async () => {
    const sql = `
      CREATE TABLE test (
        a DECIMAL(10) NOT NULL,
        b DECIMAL(10) NOT NULL,
        PRIMARY KEY (a, b)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    const pkCols = result.tables[0].columns.filter(c => c.primaryKey);
    expect(pkCols).toHaveLength(2);
  });

  // --- UNIQUE ---
  it('handles UNIQUE constraint', async () => {
    const sql = `
      CREATE TABLE test (
        id DECIMAL(10) NOT NULL,
        email VARCHAR(255) UNIQUE,
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    const emailCol = result.tables[0].columns.find(c => c.name === 'email')!;
    expect(emailCol.unique).toBe(true);
  });

  // --- DEFAULT ---
  it('handles DEFAULT values', async () => {
    const sql = `
      CREATE TABLE test (
        id DECIMAL(10) NOT NULL,
        status VARCHAR(20) DEFAULT 'active'
      );
    `;
    const result = await importDDL(sql, 'oracle');
    const statusCol = result.tables[0].columns.find(c => c.name === 'status')!;
    expect(statusCol.defaultValue).toBe("'active'");
  });

  // --- NOT NULL ---
  it('distinguishes nullable vs NOT NULL', async () => {
    const sql = `
      CREATE TABLE test (
        a DECIMAL(10) NOT NULL,
        b VARCHAR(100)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].columns[0].nullable).toBe(false);
    expect(result.tables[0].columns[1].nullable).toBe(true);
  });

  // --- Multiple tables ---
  it('parses multiple tables', async () => {
    const sql = `
      CREATE TABLE t1 (id DECIMAL(10) NOT NULL, PRIMARY KEY (id));
      CREATE TABLE t2 (id DECIMAL(10) NOT NULL, PRIMARY KEY (id));
      CREATE TABLE t3 (id DECIMAL(10) NOT NULL, PRIMARY KEY (id));
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables).toHaveLength(3);
  });

  // --- Double-quoted identifiers ---
  it('handles double-quoted identifiers', async () => {
    const sql = `
      CREATE TABLE "MY_TABLE" (
        "MY_COL" DECIMAL(10) NOT NULL,
        PRIMARY KEY ("MY_COL")
      );
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.errors).toHaveLength(0);
    expect(result.tables[0].name).toBe('MY_TABLE');
    expect(result.tables[0].columns[0].name).toBe('MY_COL');
  });

  // --- Schema prefix ---
  it('extracts schema from qualified table name', async () => {
    const sql = `
      CREATE TABLE "HR"."employees" (
        "id" DECIMAL(10) NOT NULL,
        PRIMARY KEY ("id")
      );
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].schema).toBe('HR');
    expect(result.tables[0].name).toBe('employees');
  });

  // --- Error ---
  it('returns error for empty input', async () => {
    const result = await importDDL('', 'oracle');
    expect(result.errors.length).toBeGreaterThan(0);
  });

  // --- CHECK ---
  it('extracts CHECK constraint', async () => {
    const sql = `
      CREATE TABLE test (
        price DECIMAL(10,2) CHECK (price > 0),
        name VARCHAR(100),
        PRIMARY KEY (price)
      );
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].columns.find(c => c.name === 'price')!.check).toBe('price > 0');
  });

  // --- INDEX ---
  it('parses CREATE INDEX', async () => {
    const sql = `
      CREATE TABLE users (
        id DECIMAL(10) NOT NULL,
        email VARCHAR(255),
        PRIMARY KEY (id)
      );
      CREATE INDEX idx_email ON users (email);
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].indexes).toHaveLength(1);
  });

  it('parses CREATE UNIQUE INDEX', async () => {
    const sql = `
      CREATE TABLE users (
        id DECIMAL(10) NOT NULL,
        email VARCHAR(255),
        PRIMARY KEY (id)
      );
      CREATE UNIQUE INDEX idx_email_uq ON users (email);
    `;
    const result = await importDDL(sql, 'oracle');
    expect(result.tables[0].indexes[0].unique).toBe(true);
  });
});

// ═════════════════════════════════════════════
// H2
// ═════════════════════════════════════════════
describe('importDDL — H2', () => {
  // --- Basic parsing ---
  it('parses basic CREATE TABLE', async () => {
    const sql = `
      CREATE TABLE test (
        id INT NOT NULL,
        data TEXT,
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.errors).toHaveLength(0);
    expect(result.tables).toHaveLength(1);
  });

  // --- Type mapping ---
  it('maps CLOB → TEXT', async () => {
    const sql = `
      CREATE TABLE test (
        id INT NOT NULL,
        data TEXT
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].columns.find(c => c.name === 'data')!.type).toBe('TEXT');
  });

  it('handles all standard types: INT, BIGINT, VARCHAR, BOOLEAN, UUID, DECIMAL', async () => {
    const sql = `
      CREATE TABLE type_test (
        c_int INT,
        c_bigint BIGINT,
        c_varchar VARCHAR(100),
        c_boolean BOOLEAN,
        c_uuid UUID,
        c_decimal DECIMAL(10,2),
        c_float FLOAT,
        c_double DOUBLE,
        c_date DATE,
        c_timestamp TIMESTAMP
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.errors).toHaveLength(0);
    const cols = result.tables[0].columns;
    expect(cols.find(c => c.name === 'c_int')!.type).toBe('INT');
    expect(cols.find(c => c.name === 'c_bigint')!.type).toBe('BIGINT');
    expect(cols.find(c => c.name === 'c_varchar')!.type).toBe('VARCHAR');
    expect(cols.find(c => c.name === 'c_boolean')!.type).toBe('BOOLEAN');
    expect(cols.find(c => c.name === 'c_uuid')!.type).toBe('UUID');
    expect(cols.find(c => c.name === 'c_decimal')!.type).toBe('DECIMAL');
    expect(cols.find(c => c.name === 'c_decimal')!.length).toBe(10);
    expect(cols.find(c => c.name === 'c_decimal')!.scale).toBe(2);
  });

  // --- IDENTITY ---
  it('detects GENERATED BY DEFAULT AS IDENTITY', async () => {
    const sql = `
      CREATE TABLE test (
        id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR(100),
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'h2');
    const idCol = result.tables[0].columns.find(c => c.name === 'id')!;
    expect(idCol.autoIncrement).toBe(true);
  });

  it('detects GENERATED ALWAYS AS IDENTITY', async () => {
    const sql = `
      CREATE TABLE test (
        id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
        name VARCHAR(100),
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].columns.find(c => c.name === 'id')!.autoIncrement).toBe(true);
  });

  it('detects AUTO_INCREMENT', async () => {
    const sql = `
      CREATE TABLE test (
        id INT AUTO_INCREMENT NOT NULL,
        name VARCHAR(100),
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].columns.find(c => c.name === 'id')!.autoIncrement).toBe(true);
  });

  // --- COMMENT ON ---
  it('applies COMMENT ON TABLE and COLUMN', async () => {
    const sql = `
      CREATE TABLE items (
        id INT NOT NULL,
        name VARCHAR(100)
      );
      COMMENT ON TABLE items IS 'Item table';
      COMMENT ON COLUMN items.name IS 'Item name';
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].comment).toBe('Item table');
    expect(result.tables[0].columns.find(c => c.name === 'name')!.comment).toBe('Item name');
  });

  it('handles multiple COMMENT ON for different columns', async () => {
    const sql = `
      CREATE TABLE test (
        a INT NOT NULL,
        b VARCHAR(100),
        c TEXT
      );
      COMMENT ON COLUMN test.a IS 'Column A';
      COMMENT ON COLUMN test.b IS 'Column B';
      COMMENT ON COLUMN test.c IS 'Column C';
    `;
    const result = await importDDL(sql, 'h2');
    const cols = result.tables[0].columns;
    expect(cols.find(c => c.name === 'a')!.comment).toBe('Column A');
    expect(cols.find(c => c.name === 'b')!.comment).toBe('Column B');
    expect(cols.find(c => c.name === 'c')!.comment).toBe('Column C');
  });

  // --- PK ---
  it('handles composite primary key', async () => {
    const sql = `
      CREATE TABLE test (
        a INT NOT NULL,
        b INT NOT NULL,
        PRIMARY KEY (a, b)
      );
    `;
    const result = await importDDL(sql, 'h2');
    const pkCols = result.tables[0].columns.filter(c => c.primaryKey);
    expect(pkCols).toHaveLength(2);
  });

  // --- UNIQUE ---
  it('handles inline UNIQUE', async () => {
    const sql = `
      CREATE TABLE test (
        id INT PRIMARY KEY,
        email VARCHAR(255) UNIQUE
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].columns.find(c => c.name === 'email')!.unique).toBe(true);
  });

  it('handles composite UNIQUE constraint', async () => {
    const sql = `
      CREATE TABLE test (
        a INT,
        b INT,
        UNIQUE (a, b)
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].uniqueKeys).toHaveLength(1);
    expect(result.tables[0].uniqueKeys[0].columnIds).toHaveLength(2);
  });

  // --- FK ---
  it('handles inline FOREIGN KEY', async () => {
    const sql = `
      CREATE TABLE parent (
        id INT NOT NULL,
        PRIMARY KEY (id)
      );
      CREATE TABLE child (
        id INT NOT NULL,
        parent_id INT NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY (parent_id) REFERENCES parent (id) ON DELETE CASCADE
      );
    `;
    const result = await importDDL(sql, 'h2');
    const child = result.tables.find(t => t.name === 'child')!;
    expect(child.foreignKeys).toHaveLength(1);
    expect(child.foreignKeys[0].onDelete).toBe('CASCADE');
  });

  it('handles ALTER TABLE FK', async () => {
    const sql = `
      CREATE TABLE parent (
        id INT NOT NULL,
        PRIMARY KEY (id)
      );
      CREATE TABLE child (
        id INT NOT NULL,
        parent_id INT NOT NULL,
        PRIMARY KEY (id)
      );
      ALTER TABLE child ADD CONSTRAINT fk_parent
        FOREIGN KEY (parent_id) REFERENCES parent (id);
    `;
    const result = await importDDL(sql, 'h2');
    const child = result.tables.find(t => t.name === 'child')!;
    expect(child.foreignKeys).toHaveLength(1);
  });

  // --- DEFAULT ---
  it('handles DEFAULT values', async () => {
    const sql = `
      CREATE TABLE test (
        id INT NOT NULL,
        status VARCHAR(20) DEFAULT 'pending',
        count INT DEFAULT 0
      );
    `;
    const result = await importDDL(sql, 'h2');
    const cols = result.tables[0].columns;
    expect(cols.find(c => c.name === 'status')!.defaultValue).toBe("'pending'");
    expect(cols.find(c => c.name === 'count')!.defaultValue).toBe('0');
  });

  // --- NOT NULL ---
  it('distinguishes nullable vs NOT NULL', async () => {
    const sql = `
      CREATE TABLE test (
        a INT NOT NULL,
        b VARCHAR(100)
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].columns[0].nullable).toBe(false);
    expect(result.tables[0].columns[1].nullable).toBe(true);
  });

  // --- CHECK ---
  it('extracts CHECK constraint', async () => {
    const sql = `
      CREATE TABLE test (
        age INT CHECK (age >= 0),
        name VARCHAR(100),
        PRIMARY KEY (age)
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].columns.find(c => c.name === 'age')!.check).toBe('age >= 0');
  });

  // --- INDEX ---
  it('parses CREATE INDEX', async () => {
    const sql = `
      CREATE TABLE users (
        id INT NOT NULL,
        email VARCHAR(255),
        PRIMARY KEY (id)
      );
      CREATE INDEX idx_email ON users (email);
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].indexes).toHaveLength(1);
    expect(result.tables[0].indexes[0].name).toBe('idx_email');
  });

  it('parses CREATE UNIQUE INDEX', async () => {
    const sql = `
      CREATE TABLE users (
        id INT NOT NULL,
        email VARCHAR(255),
        PRIMARY KEY (id)
      );
      CREATE UNIQUE INDEX idx_email_uq ON users (email);
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].indexes[0].unique).toBe(true);
  });

  // --- Schema ---
  it('extracts schema from qualified table name', async () => {
    const sql = `
      CREATE TABLE "app"."users" (
        id INT NOT NULL,
        PRIMARY KEY (id)
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables[0].schema).toBe('app');
    expect(result.tables[0].name).toBe('users');
  });

  // --- Multiple tables ---
  it('parses multiple tables', async () => {
    const sql = `
      CREATE TABLE a (id INT NOT NULL, PRIMARY KEY (id));
      CREATE TABLE b (id INT NOT NULL, PRIMARY KEY (id));
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.tables).toHaveLength(2);
  });

  // --- Error ---
  it('returns error for empty input', async () => {
    const result = await importDDL('', 'h2');
    expect(result.errors.length).toBeGreaterThan(0);
  });

  // --- Double-quoted identifiers ---
  it('handles double-quoted identifiers', async () => {
    const sql = `
      CREATE TABLE "MY_TABLE" (
        "MY_COL" INT NOT NULL,
        PRIMARY KEY ("MY_COL")
      );
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.errors).toHaveLength(0);
    expect(result.tables[0].name).toBe('MY_TABLE');
    expect(result.tables[0].columns[0].name).toBe('MY_COL');
  });

  // --- Real-world: Spring Session H2 ---
  it('parses Spring Session H2 DDL with bracket identifiers', async () => {
    const sql = `
      CREATE TABLE [SPRING_SESSION] (
        [PRIMARY_ID] CHAR(36) NOT NULL,
        [SESSION_ID] CHAR(36) NOT NULL,
        [CREATION_TIME] BIGINT NOT NULL,
        [LAST_ACCESS_TIME] BIGINT NOT NULL,
        [MAX_INACTIVE_INTERVAL] INT NOT NULL,
        [EXPIRY_TIME] BIGINT NOT NULL,
        [PRINCIPAL_NAME] VARCHAR(100),
        PRIMARY KEY ([PRIMARY_ID])
      );
      CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
    `;
    const result = await importDDL(sql, 'h2');
    expect(result.errors).toHaveLength(0);
    expect(result.tables).toHaveLength(1);
    expect(result.tables[0].name).toBe('SPRING_SESSION');
    expect(result.tables[0].columns).toHaveLength(7);
    expect(result.tables[0].indexes).toHaveLength(1);
    expect(result.tables[0].indexes[0].unique).toBe(true);
  });
});
