export interface OraclePreprocessResult {
  cleanedSql: string;
  tableComments: Map<string, string>;
  colComments: Map<string, Map<string, string>>;
  identityColumns: Map<string, Set<string>>;
}

export function preprocessOracle(sql: string): OraclePreprocessResult {
  const tableComments = new Map<string, string>();
  const colComments = new Map<string, Map<string, string>>();
  const identityColumns = new Map<string, Set<string>>();

  // Extract COMMENT ON TABLE
  const tableCommentRe = /COMMENT\s+ON\s+TABLE\s+(?:"\w+"\.)?"?(\w+)"?\s+IS\s+'([^']*)'/gi;
  let m: RegExpExecArray | null;
  while ((m = tableCommentRe.exec(sql)) !== null) {
    tableComments.set(m[1], m[2]);
  }

  // Extract COMMENT ON COLUMN
  const colCommentRe = /COMMENT\s+ON\s+COLUMN\s+(?:"\w+"\.)?"?(\w+)"?\."?(\w+)"?\s+IS\s+'([^']*)'/gi;
  while ((m = colCommentRe.exec(sql)) !== null) {
    if (!colComments.has(m[1])) colComments.set(m[1], new Map());
    colComments.get(m[1])!.set(m[2], m[3]);
  }

  // Extract IDENTITY columns (GENERATED ... AS IDENTITY)
  const tableHeaderRe = /CREATE\s+TABLE\s+(?:"\w+"\.)?"?(\w+)"?\s*\(/gi;
  while ((m = tableHeaderRe.exec(sql)) !== null) {
    const tableName = m[1];
    // Use paren depth tracking to find matching ')'
    let depth = 1, idx = m.index + m[0].length;
    const bodyStart = idx;
    while (idx < sql.length && depth > 0) {
      if (sql[idx] === '(') depth++;
      else if (sql[idx] === ')') depth--;
      idx++;
    }
    if (depth !== 0) continue;
    const body = sql.slice(bodyStart, idx - 1);
    const identityRe = /^\s*"?(\w+)"?\s+.*GENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY/gim;
    let cm: RegExpExecArray | null;
    while ((cm = identityRe.exec(body)) !== null) {
      if (!identityColumns.has(tableName)) identityColumns.set(tableName, new Set());
      identityColumns.get(tableName)!.add(cm[1]);
    }
  }

  let cleaned = sql;
  // Remove COMMENT ON statements
  cleaned = cleaned.replace(/COMMENT\s+ON\s+(?:TABLE|COLUMN)\s+[^;]*;/gi, '');
  // Remove ALTER TABLE FK statements (will be re-parsed)
  // Remove Oracle-specific syntax
  cleaned = cleanOracleSyntax(cleaned);

  return { cleanedSql: cleaned, tableComments, colComments, identityColumns };
}

export function cleanOracleSyntax(sql: string): string {
  // Remove / batch separators (Oracle SQL*Plus)
  sql = sql.replace(/^\s*\/\s*$/gm, '');
  // Remove GENERATED ... AS IDENTITY
  sql = sql.replace(/\bGENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY(?:\s*\([^)]*\))?/gi, '');
  // VARCHAR2 → VARCHAR
  sql = sql.replace(/\bVARCHAR2\b/gi, 'VARCHAR');
  // NVARCHAR2 → VARCHAR
  sql = sql.replace(/\bNVARCHAR2\b/gi, 'VARCHAR');
  // NUMBER → DECIMAL
  sql = sql.replace(/\bNUMBER\b/gi, 'DECIMAL');
  // CLOB/NCLOB → TEXT
  sql = sql.replace(/\bNCLOB\b/gi, 'TEXT');
  sql = sql.replace(/\bCLOB\b/gi, 'TEXT');
  // BINARY_DOUBLE → DOUBLE PRECISION
  sql = sql.replace(/\bBINARY_DOUBLE\b/gi, 'DOUBLE PRECISION');
  // BINARY_FLOAT → FLOAT
  sql = sql.replace(/\bBINARY_FLOAT\b/gi, 'FLOAT');
  // RAW(...) → TEXT
  sql = sql.replace(/\bRAW\s*\(\s*\d+\s*\)/gi, 'TEXT');
  // Remove Oracle keywords: ENABLE, NOVALIDATE, TABLESPACE, PCTFREE, INITRANS, etc.
  sql = sql.replace(/\bENABLE\b/gi, '');
  sql = sql.replace(/\bNOVALIDATE\b/gi, '');
  sql = sql.replace(/\bTABLESPACE\s+\w+/gi, '');
  sql = sql.replace(/\bPCTFREE\s+\d+/gi, '');
  sql = sql.replace(/\bINITRANS\s+\d+/gi, '');
  sql = sql.replace(/\bSTORAGE\s*\([^)]*\)/gi, '');
  sql = sql.replace(/\bLOGGING\b/gi, '');
  sql = sql.replace(/\bNOLOGGING\b/gi, '');
  sql = sql.replace(/\bSEGMENT\s+CREATION\s+\w+/gi, '');
  // Remove USING INDEX clause
  sql = sql.replace(/\bUSING\s+INDEX\b/gi, '');
  // Fix trailing comma before closing paren
  sql = sql.replace(/,(\s*\n?\s*\))/g, '$1');
  return sql;
}

export interface H2PreprocessResult {
  cleanedSql: string;
  tableComments: Map<string, string>;
  colComments: Map<string, Map<string, string>>;
  identityColumns: Map<string, Set<string>>;
}

export function preprocessH2(sql: string): H2PreprocessResult {
  const tableComments = new Map<string, string>();
  const colComments = new Map<string, Map<string, string>>();
  const identityColumns = new Map<string, Set<string>>();

  // Extract COMMENT ON TABLE
  const tableCommentRe = /COMMENT\s+ON\s+TABLE\s+(?:"\w+"\.)?"?(\w+)"?\s+IS\s+'([^']*)'/gi;
  let m: RegExpExecArray | null;
  while ((m = tableCommentRe.exec(sql)) !== null) {
    tableComments.set(m[1], m[2]);
  }

  // Extract COMMENT ON COLUMN
  const colCommentRe = /COMMENT\s+ON\s+COLUMN\s+(?:"\w+"\.)?"?(\w+)"?\."?(\w+)"?\s+IS\s+'([^']*)'/gi;
  while ((m = colCommentRe.exec(sql)) !== null) {
    if (!colComments.has(m[1])) colComments.set(m[1], new Map());
    colComments.get(m[1])!.set(m[2], m[3]);
  }

  // Extract IDENTITY columns (GENERATED BY DEFAULT AS IDENTITY / AUTO_INCREMENT)
  const tableHeaderReH2 = /CREATE\s+TABLE\s+(?:"\w+"\.)?"?(\w+)"?\s*\(/gi;
  while ((m = tableHeaderReH2.exec(sql)) !== null) {
    const tableName = m[1];
    let depth = 1, idx = m.index + m[0].length;
    const bodyStart = idx;
    while (idx < sql.length && depth > 0) {
      if (sql[idx] === '(') depth++;
      else if (sql[idx] === ')') depth--;
      idx++;
    }
    if (depth !== 0) continue;
    const body = sql.slice(bodyStart, idx - 1);
    const identityRe = /^\s*"?(\w+)"?\s+.*(?:GENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY|AUTO_INCREMENT)/gim;
    let cm: RegExpExecArray | null;
    while ((cm = identityRe.exec(body)) !== null) {
      if (!identityColumns.has(tableName)) identityColumns.set(tableName, new Set());
      identityColumns.get(tableName)!.add(cm[1]);
    }
  }

  let cleaned = sql;
  // Remove COMMENT ON statements
  cleaned = cleaned.replace(/COMMENT\s+ON\s+(?:TABLE|COLUMN)\s+[^;]*;/gi, '');
  // Remove IDENTITY keywords
  cleaned = cleaned.replace(/\bGENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY(?:\s*\([^)]*\))?/gi, '');
  cleaned = cleaned.replace(/\bAUTO_INCREMENT\b/gi, '');
  // Fix trailing comma before closing paren
  cleaned = cleaned.replace(/,(\s*\n?\s*\))/g, '$1');

  return { cleanedSql: cleaned, tableComments, colComments, identityColumns };
}
